name: Cache node_modules
description: Cache node_modules after install
runs:
  using: composite
  steps:
    - name: Cache node_modules
      uses: actions/cache@v2
      id: yarn-cache
      with:
        path: |
          **/node_modules
        key: yarn-cache-${{ hashFiles('**/yarn.lock') }}
    - name: Install Dependencies
      if: steps.yarn-cache.outputs.cache-hit != 'true'
      shell: bash
      run: corepack enable && yarn install --immutable
    - name: Post Install
      shell: bash
      run: yarn run postinstall
